language: node_js
node_js:
   - "0.12.0"

env:
  matrix:
    - COVERALLS_SERVICE_NAME=travis-ci
  global:
    - secure: gwwr+ya3NF+1NLxbR6bx3pFK3LAwywVBUrITyGGYnPFq4XI6nHBJxlLsFMOSx7Qzs4Vsw/P4Qm11BubUWxOqxpmGI4d4770ik0tNVsA1XfFzgIej9zHU8iM80wdnqObazsiwmo8iK077RM0Y8/X/ZF1oeC6UFtccMLv6yzOdnOkqYpf8b0ex4qhyzv/odhv0EfC8K4+jR1q8s/qQGP/ZQ2yEXE91FCgoKPkARa6eHvoPS5aC+ZTrdwgMoFmA7H70EjmgESOwj4ZSE8yeL/zBHWI1RlqRSEreWp5RKMZeycxuGp6ip2Lp30gEkYSlkWoi0PKmGuMHHAV05rtm1qR3bkx4Gx5+3F46s6IPt26mKvjUtHHenMBlacAsW07g3p1czhqWqO7E3vNBYKjzwRfvzq4GXv3i6Xo4LvQIR89Apte932bGZnCdvULul9iYRKhH5bJrplHTtVGPDNS9FuFShAj/j8AXH7ayDboivoxOZtCaTfxVxRjlUcQJLxP46vrcogA6lPkguTELzPSZKJKlLGWVJk9N0Rrq7ZuAYz8Ds8FrtX4w3jvfDCcfTU9sY/XtQTDFUVkdeat/JnYdp7rsfx1jvSKr1+a69SyuPd+S3PbAHBmveJbBOfjO/WbCvChDbj/tBD+aABJLeUUKnO+XCjwKOfNIFqtCH07qjkpsdAc=
    - secure: KFXQ0O5Zp4ulvwSuFEnZUjWxRKMpsL+q/4zydHBo/hxTCgcnGydh9QJnbfHkpHfi9wAenfowaFSdM0OrfIU2II484oZtblY2ZP+rWyqp1nWH66fgITjZKvTiGUZ8WLwwVO9tsdYb7dXZnIv+v1oGuTB8EmWwFPU0jX/xgpgTnZ5Mu2AdtgsFuALQ8hIOb+f4di6ffyN7bsCpJW4ez0i/5f/SEm3DGee+BuFAFkyYoneseW26BhgmMc7dnpOqvxk065U70r6ZrwL8zhKIGUWVAlzOqswWEjTKYKguljFY4UsHptk6kQRB6xdBy9oZjVklEQf/1/6Q3sPHbJweGs/2XT2xJa74xsdGQUNnUKx6a6ZohBlmWglOsVJ8busmFfwUnxtT01Db1MD1Q2VBR82WobtB22iL440rXWMxOqnzOHPJF3vvtWYmtHvrVvuH0d+24Py2M17gaDyzC8nAOIsnCk7igybhRlOybnxOpOeJz+6xEg9pmGG9GuX9f89De2Vb7zuF9D11vZb/SNiIGACLxxMItYs9/JZFT1vtMCvA+5NQSlKjroznTCyNMG37VynYTeThzS/SB9+zSHfupxy5rb43vEN2CCnkVgYg1JkWpzCl9JHcKQ5X4wwBdKFIb+9AhUwKxQH/9o9/EVYnqoUGV+Dpnycj1wIJJ/HRGfnIqw4=
    - secure: cD5y0hfL5XWekPOmslU6SDsl8brXS6c8h4yraG169PY4LfBwiVtX/r2GTkLcxesedgTkCV5PNWGXkRJr9OEs+SN8s/VUlO1l0J+wj4VOvQaI7kK1uhEFUKwGmIkV+AwbO0SZZ9GphV0xvNICnp81VTsDCo4meWq43ZfPrHPwZyHGqAc3YZX4zVYxphFbfZvpyXo5/sTXtHzaQAkc48xAbZcLLchU6SfjL/XhwqzHzWEeYUQ46Y5VLs5foypClSZAx8CNEw/fjevsLs1nnJ4QOmrBUOA4n4b9muHactUL66kZvRmmrkl/JHh8cxH7Ip1TJHJvFVTFE2IsDQwfl/w6HtzCy8dvL9DmgTfmxRy6COoqTpFXGGkakrRsK5fysdhHnE2HZHDSCZj48nOe/NoyyYTOQsipnAeYecyHqWnclUMxkm84ZbLwYUO666fhQdFg2BSshiHrOR9lKRR5woiYvip1s0c51NRiI5jzysd+8rNv55hZLeXH+pzUcl1Pl1hG2/0M0PDXaVsWYqg8z2EARhQaxHZlmxE2BdJPspHKqpr2GFAESE2jCvLBTNHnp0qIL++J+K5fAh7vFu7uCXUHT29RFIVftGCWLXQ3z4nZrFLUsgYU1p3dR4wXudUF0tpmfQi4Rjhi+SsRQLC3YuxOGxInb9DdMWvJXR8a34utjno=

before_script:
  - gulp autopolyfiller

script:
  - npm test && gulp build

after_script:
  - istanbul cover src/heartbeat.js

sudo: false

install:
  - npm install gulp -g
  - npm install karma-cli -g
  - npm install istanbul -g
  - npm install

notifications:
    email: false

addons:
  sauce_connect: true
